version: "3.7"

services:

  api:
    build:
      dockerfile: "${PWD}/Dockerfile"
      context: "${PWD}"
    volumes:
      - "${PWD}:/src"
    expose:
      - "8000"
    ports:
      - 4481:8000
    restart: always


  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/html
    links:
      - api:api
    ports:
      - 4480:80


